//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadIlvinaPP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChildrenParent
    {
        public int IdChildrenParent { get; set; }
        public Nullable<int> ChildrenId { get; set; }
        public Nullable<int> ParentId { get; set; }
    
        public virtual Children Children { get; set; }
        public virtual Parent Parent { get; set; }
    }
}
