//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadIlvinaPP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public int IdVisit { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> IsPresence { get; set; }
        public Nullable<int> ChildrenId { get; set; }
    
        public virtual Children Children { get; set; }
    }
}
